# Collector specific configuration
url: "https://www.glidenumber.net/glide/jsonglideset.jsp"
event_types:
  AC: "tech. disaster"
  AV: "snow avalanche"
  CE: "complex emergency"
  CW: "cold wave"
  DR: "drought"
  EC: "extratropical cyclone"
  EP: "epidemic"
  EQ: "earthquake"
  ET: "extreme temperature"
  FA: "famine"
  FF: "flash flood"
  FL: "flood"
  FR: "fire"
  HT: "heat wave"
  IN: "insect infestation"
  LS: "land slide"
  MS: "mud slide"
  OT: "other"
  SL: "slide"
  SS: "storm surge"
  ST: "severe local storm"
  TC: "tropical cyclone"
  TO: "tornadoes"
  TS: "tsunami"
  VO: "volcano"
  VW: "violent wind"
  WF: "wild fire"
  WV: "wave/surge"
