# Collector specific configuration
url: "https://www.glidenumber.net/glide/jsonglideset.jsp"
geojson_url: "https://www.glidenumber.net/glide/geojsonglideset.jsp"
event_types:
  AC: "tech. disaster"
  AV: "snow avalanche"
  CE: "complex emergency"
  CW: "cold wave"
  DR: "drought"
  EC: "extratropical cyclone"
  EP: "epidemic"
  EQ: "earthquake"
  ET: "extreme temperature"
  FA: "famine"
  FF: "flash flood"
  FL: "flood"
  FR: "fire"
  HT: "heat wave"
  IN: "insect infestation"
  LS: "land slide"
  MS: "mud slide"
  OT: "other"
  SL: "slide"
  SS: "storm surge"
  ST: "severe local storm"
  TC: "tropical cyclone"
  TO: "tornadoes"
  TS: "tsunami"
  VO: "volcano"
  VW: "violent wind"
  WF: "wild fire"
  WV: "wave/surge"

event_tags:
  AC:
    - "hazards and risk"
  AV:
    - "natural disasters"
  CE:
    - "complex emergency-conflict-security"
  CW:
    - "climate hazards"
    - "natural disasters"
  DR:
    - "drought"
    - "climate hazards"
    - "natural disasters"
  EC:
    - "cyclones-hurricanes-typhoons"
    - "climate hazards"
    - "natural disasters"
  EP:
    - "epidemics-outbreaks"
    - "disease"
    - "health"
  EQ:
    - "earthquake-tsunami"
    - "natural disasters"
  ET:
    - "climate hazards"
    - "natural disasters"
  FA:
    - "food security"
    - "malnutrition"
  FF:
    - "flooding"
    - "natural disasters"
  FL:
    - "flooding"
    - "natural disasters"
  FR:
    - "climate hazards"
    - "natural disasters"
  HT:
    - "climate hazards"
    - "natural disasters"
  IN:
    - "agriculture-livestock"
    - "food security"
  LS:
    - "natural disasters"
  MS:
    - "natural disasters"
  OT:
    - "hazards and risk"
  SL:
    - "natural disasters"
  SS:
    - "flooding"
    - "cyclones-hurricanes-typhoons"
    - "natural disasters"
  ST:
    - "climate hazards"
    - "natural disasters"
  TC:
    - "climate hazards"
    - "cyclones-hurricanes-typhoons"
    - "natural disasters"
  TO:
    - "climate hazards"
    - "natural disasters"
  TS:
    - "earthquake-tsunami"
    - "flooding"
    - "natural disasters"
  VO:
    - "natural disasters"
  VW:
    - "climate hazards"
    - "natural disasters"
  WF:
    - "climate hazards"
    - "natural disasters"
  WV:
    - "flooding"
    - "natural disasters"
